// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxpvtinvevyzjrvbtpph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54cHZ0aW52ZXZ5empydmJ0cHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjQ0MTQsImV4cCI6MjA2ODA0MDQxNH0.hBZggtd6p29qWx-bzs-OcL0exa5rwxeZq9twPuugfDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});